package Calculadora;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Calcu extends javax.swing.JFrame {

ImagenFondo Fondo;
private float num1;
private float num2;
private String simbolo;
private boolean resu = false;

    public Calcu() {

    Fondo = new ImagenFondo("src/iconos/CiervoBosque.jpg");
    this.setContentPane(Fondo);

        initComponents();
    }

@Override
public Image getIconImage(){

    Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconos/LogoZorro.png"));
    return valorRetorno;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        TextModif = new javax.swing.JTextField();
        multi = new javax.swing.JButton();
        division = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        retoceso = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        modulo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Salir = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora del Zorro.exe");
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("El Zorro Matematico");

        siete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (7).png"))); // NOI18N
        siete.setToolTipText("");
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (8).png"))); // NOI18N
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        nueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (9).png"))); // NOI18N
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (4).png"))); // NOI18N
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (5).png"))); // NOI18N
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (6).png"))); // NOI18N
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (1).png"))); // NOI18N
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (2).png"))); // NOI18N
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (3).png"))); // NOI18N
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/numero (0).png"))); // NOI18N
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        TextModif.setBackground(new java.awt.Color(51, 51, 51));
        TextModif.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        TextModif.setForeground(new java.awt.Color(255, 255, 255));
        TextModif.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        multi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/multiplicacion.png"))); // NOI18N
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });

        division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/division.png"))); // NOI18N
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas.png"))); // NOI18N
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menos.png"))); // NOI18N
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/igual.png"))); // NOI18N
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        retoceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        retoceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retocesoActionPerformed(evt);
            }
        });

        potencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/potencia.png"))); // NOI18N
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });

        modulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/módulo.png"))); // NOI18N
        modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TextModif, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(siete)
                        .addGap(18, 18, 18)
                        .addComponent(ocho)
                        .addGap(18, 18, 18)
                        .addComponent(nueve))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cuatro)
                        .addGap(18, 18, 18)
                        .addComponent(cinco)
                        .addGap(18, 18, 18)
                        .addComponent(seis))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uno)
                        .addGap(18, 18, 18)
                        .addComponent(dos)
                        .addGap(18, 18, 18)
                        .addComponent(tres)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(suma)
                        .addComponent(potencia)
                        .addComponent(multi))
                    .addComponent(igual))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(division)
                            .addComponent(resta)
                            .addComponent(retoceso))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TextModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(igual)
                            .addComponent(retoceso))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(division)
                            .addComponent(multi))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(suma)
                            .addComponent(resta))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(potencia)
                            .addComponent(modulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(siete)
                            .addComponent(ocho)
                            .addComponent(nueve))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuatro)
                            .addComponent(cinco)
                            .addComponent(seis))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uno)
                            .addComponent(dos)
                            .addComponent(tres))
                        .addGap(34, 34, 34)
                        .addComponent(cero)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(520, 513));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
    int valor;

    ImageIcon icono = new ImageIcon("src/iconos/LogoZorroChiquito.png");
    valor = JOptionPane.showConfirmDialog(this, "¿Quieres salir? TnT", "Saliendo de la aplicacion. . .", JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE, icono);

        if(valor == 0){

        this.dispose();

        }else{

        ImageIcon icono2 = new ImageIcon("src/iconos/CaraZorro.png");
        JOptionPane.showMessageDialog(null, "Pues sigamos calculando ^w^", "Continuemos. . .", JOptionPane.WARNING_MESSAGE, icono2);

        }
    }//GEN-LAST:event_SalirMouseClicked

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed

        num2 = Float.parseFloat(TextModif.getText());
        switch(simbolo){

            case "+":
                TextModif.setText(Float.toString(num1 + num2));
                break;

            case "-":
                TextModif.setText(Float.toString(num1 - num2));
                break;

            case "x":
                TextModif.setText(Float.toString(num1 * num2));
                break;

            case "/":
                TextModif.setText(Float.toString(num1 / num2));
                break;

            case "%":
                TextModif.setText(Float.toString(num1 % num2));
                break;

            case "^":
                TextModif.setText(Double.toString(Math.pow(num1, num2)));
                break;
        }

        resu = true;
    }//GEN-LAST:event_igualActionPerformed

    private void retocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retocesoActionPerformed
        TextModif.setText("");
    }//GEN-LAST:event_retocesoActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "x";
        TextModif.setText("");
    }//GEN-LAST:event_multiActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "/";
        TextModif.setText("");
    }//GEN-LAST:event_divisionActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "+";
        TextModif.setText("");
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "-";
        TextModif.setText("");
    }//GEN-LAST:event_restaActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "^";
        TextModif.setText("");
    }//GEN-LAST:event_potenciaActionPerformed

    private void moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloActionPerformed

        num1 = Float.parseFloat(TextModif.getText());
        simbolo = "%";
        TextModif.setText("");
    }//GEN-LAST:event_moduloActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "0");
        resu = false; 
    }//GEN-LAST:event_ceroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "1");
        resu = false;
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "2");
        resu = false;
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "3");
        resu = false;
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "4");
        resu = false;
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "5");
        resu = false;
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed

        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "6");
        resu = false;
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        
        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "7");
        resu = false;
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        
        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "8");
        resu = false;
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        
        if(resu == true)
            TextModif.setText("");

        TextModif.setText(TextModif.getText() + "9");
        resu = false;
    }//GEN-LAST:event_nueveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Salir;
    private javax.swing.JTextField TextModif;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton division;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton modulo;
    private javax.swing.JButton multi;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton potencia;
    private javax.swing.JButton resta;
    private javax.swing.JButton retoceso;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}