package Biblioteca;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

public class JPréstamo extends javax.swing.JFrame {
    
    Pila Alumno;
    Pila prestam;
    Pila libro;

    ImagenFondo Fondo;

    public JPréstamo(Pila alumno,Pila prestam,Pila libro) {

        Fondo = new  ImagenFondo("src/Icon/Prestamo.jpg");
        this.setContentPane(Fondo);

        initComponents();

        this.Alumno = alumno;
        this.prestam = prestam;
        this.libro = libro;
    }

    public Image getIconImage(){

    Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Icon/logozorro.png"));
    return valorRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NL = new javax.swing.JLabel();
        gene = new javax.swing.JLabel();
        numpag = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Regreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FP = new javax.swing.JTextField();
        FR = new javax.swing.JTextField();
        retraso = new javax.swing.JTextField();
        AM = new javax.swing.JTextField();
        TextModif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prestamo.exe");
        setIconImage(getIconImage());
        setResizable(false);

        NL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NL.setForeground(new java.awt.Color(255, 255, 255));
        NL.setText("Fecha de regreso:");

        gene.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        gene.setForeground(new java.awt.Color(255, 255, 255));
        gene.setText("Prorroga:");

        numpag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        numpag.setForeground(new java.awt.Color(255, 255, 255));
        numpag.setText("Amonestacion monetaria:");
        numpag.setToolTipText("");

        Agregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/verificado.png"))); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu de ingreso de datos de Prestamo");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/basura.png"))); // NOI18N
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Regreso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Regreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/volver.png"))); // NOI18N
        Regreso.setText("Regresar");
        Regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha de Prestamo:");

        FP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FPMouseExited(evt);
            }
        });

        FR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FRMouseExited(evt);
            }
        });

        retraso.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        retraso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retrasoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                retrasoMouseExited(evt);
            }
        });

        AM.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AMMouseExited(evt);
            }
        });

        TextModif.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TextModif.setForeground(new java.awt.Color(255, 255, 255));
        TextModif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextModif.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextModif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numpag)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Agregar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 28, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(49, 49, 49)
                                .addComponent(Regreso)
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(AM, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(FP))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(NL)
                            .addGap(18, 18, 18)
                            .addComponent(FR))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(gene)
                            .addGap(18, 18, 18)
                            .addComponent(retraso, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NL, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FR, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gene, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpag, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TextModif)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed

        Préstamo prestamo = new Préstamo();        
        prestamo.setFechaP(FP.getText());
        prestamo.setFechaR(FR.getText());
        prestamo.setProrroga(retraso.getText());
        prestamo.setIncumpli(AM.getText());

            TextModif.setText("Datos Guardados");
            prestam.push(prestamo);      

        FP.setText("");
        FR.setText("");
        retraso.setText("");
        AM.setText("");
        FP.requestFocus();  
    }//GEN-LAST:event_AgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prestam.eliminar();
        TextModif.setText("Se a eliminado los datos correctamente");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresoActionPerformed
       MenuPrincipal menu = new MenuPrincipal(Alumno,prestam,libro);
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_RegresoActionPerformed

    private void FPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPMouseEntered
        FP.setBackground(Color.lightGray);
    }//GEN-LAST:event_FPMouseEntered

    private void FPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FPMouseExited
        FP.setBackground(Color.white);
    }//GEN-LAST:event_FPMouseExited

    private void FRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FRMouseEntered
        FR.setBackground(Color.lightGray);
    }//GEN-LAST:event_FRMouseEntered

    private void FRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FRMouseExited
        FR.setBackground(Color.white);
    }//GEN-LAST:event_FRMouseExited

    private void retrasoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrasoMouseEntered
        retraso.setBackground(Color.lightGray);
    }//GEN-LAST:event_retrasoMouseEntered

    private void retrasoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retrasoMouseExited
        retraso.setBackground(Color.white);
    }//GEN-LAST:event_retrasoMouseExited

    private void AMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMMouseEntered
        AM.setBackground(Color.lightGray);
    }//GEN-LAST:event_AMMouseEntered

    private void AMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMMouseExited
        AM.setBackground(Color.white);
    }//GEN-LAST:event_AMMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPréstamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPréstamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPréstamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPréstamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JPréstamo(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AM;
    private javax.swing.JButton Agregar;
    private javax.swing.JTextField FP;
    private javax.swing.JTextField FR;
    private javax.swing.JLabel NL;
    private javax.swing.JButton Regreso;
    private javax.swing.JLabel TextModif;
    private javax.swing.JLabel gene;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel numpag;
    private javax.swing.JTextField retraso;
    // End of variables declaration//GEN-END:variables
}
