package Biblioteca;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

public class MenuPrincipal extends javax.swing.JFrame {

    Pila alumno;
    Pila prestamo;
    Pila libro;
    Alumnos aux = new Alumnos();

    ImagenFondo Fondo;

    public MenuPrincipal(Pila alumno,Pila prestamo,Pila libro) {

        Fondo = new  ImagenFondo("src/Icon/Bliblioteca.jpg");
        this.setContentPane(Fondo);

        initComponents();

        this.alumno = alumno; 
        this.prestamo = prestamo;
        this.libro = libro;

    }

    public Image getIconImage(){

    Image valorRetorno = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Icon/logozorro.png"));
    return valorRetorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resu = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        TextModi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Alumno = new javax.swing.JMenu();
        IngreAlum = new javax.swing.JMenuItem();
        MostrarA = new javax.swing.JMenuItem();
        Libro = new javax.swing.JMenu();
        IngreLibro = new javax.swing.JMenuItem();
        MostrarL = new javax.swing.JMenuItem();
        Préstamo = new javax.swing.JMenu();
        IngrePres = new javax.swing.JMenuItem();
        MostrarP = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu.exe");
        setIconImage(getIconImage());
        setResizable(false);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Resu.setViewportView(Tabla);

        TextModi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TextModi.setForeground(new java.awt.Color(255, 255, 255));
        TextModi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextModi.setText("Bienvenido al menu, que desea hacer hoy?");

        Alumno.setText("Alumno");

        IngreAlum.setText("Ingresar");
        IngreAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreAlumActionPerformed(evt);
            }
        });
        Alumno.add(IngreAlum);

        MostrarA.setText("Mostrar");
        MostrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarAActionPerformed(evt);
            }
        });
        Alumno.add(MostrarA);

        jMenuBar1.add(Alumno);

        Libro.setText("Libro");

        IngreLibro.setText("Ingresar");
        IngreLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreLibroActionPerformed(evt);
            }
        });
        Libro.add(IngreLibro);

        MostrarL.setText("Mostrar");
        MostrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarLActionPerformed(evt);
            }
        });
        Libro.add(MostrarL);

        jMenuBar1.add(Libro);

        Préstamo.setText("Préstamo");

        IngrePres.setText("Ingresar");
        IngrePres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngrePresActionPerformed(evt);
            }
        });
        Préstamo.add(IngrePres);

        MostrarP.setText("Mostrar");
        MostrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPActionPerformed(evt);
            }
        });
        Préstamo.add(MostrarP);

        jMenuBar1.add(Préstamo);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Resu)
                    .addComponent(TextModi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Resu, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextModi)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
       Ingreso menu = new Ingreso();
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_SalirMouseClicked

    private void IngreAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreAlumActionPerformed
        JAlumnos reg = new JAlumnos(alumno,prestamo,libro);
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IngreAlumActionPerformed

    private void IngreLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreLibroActionPerformed
        JLibro reg = new JLibro(alumno,prestamo,libro);
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IngreLibroActionPerformed

    private void IngrePresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngrePresActionPerformed
        JPréstamo reg = new JPréstamo(alumno,prestamo,libro);
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IngrePresActionPerformed

    private void MostrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarAActionPerformed

        Nodo arregloNodo[] = new Nodo[alumno.getcn()];
                
            arregloNodo = alumno.imprimirLista();        
            DefaultTableModel tabla = new DefaultTableModel();

                String[] cabecera = {"Registro","Nombre","Hora llegada","Vigencia C."};        
                tabla.setColumnIdentifiers(cabecera);        
                Object[] datos = new Object[4];

                    for(int i =0; i<alumno.getcn();i++){
                        datos[0] = arregloNodo[i].getAlumno().getRegistro();
                        datos[1] = arregloNodo[i].getAlumno().getNombre();
                        datos[2] = arregloNodo[i].getAlumno().getHora();
                        datos[3] = arregloNodo[i].getAlumno().getVC();
           
            alumno.Recorrer();
            tabla.addRow(datos);
                   
        TextModi.setText("Mostrando datos guardados de Alumnos");
            
        }
        Tabla.setModel(tabla);
    }//GEN-LAST:event_MostrarAActionPerformed

    private void MostrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarLActionPerformed
        Nodo arregloNodo[] = new Nodo[libro.getcn()];
                
            arregloNodo = libro.imprimirLista();        
            DefaultTableModel tabla = new DefaultTableModel();

                String[] cabecera = {"Codigo libro","Nombre libro","Genero","Mun. paginas"};        
                tabla.setColumnIdentifiers(cabecera);        
                Object[] datos = new Object[4];

                    for(int i =0; i<libro.getcn();i++){
                        datos[0] = arregloNodo[i].getLibro().getCodigoL();
                        datos[1] = arregloNodo[i].getLibro().getNombreL();
                        datos[2] = arregloNodo[i].getLibro().getGenero();
                        datos[3] = arregloNodo[i].getLibro().getNumeroPag();
           
            libro.Recorrer();
            tabla.addRow(datos);
                   
        TextModi.setText("Mostrando datos guardados de Libros");
            
        }
        Tabla.setModel(tabla);
    }//GEN-LAST:event_MostrarLActionPerformed

    private void MostrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPActionPerformed
        Nodo arregloNodo[] = new Nodo[prestamo.getcn()];
                
            arregloNodo = prestamo.imprimirLista();        
            DefaultTableModel tabla = new DefaultTableModel();

                String[] cabecera = {"Fecha prestamo","Fecha regreso","Prorroga","Amonestacion $"};        
                tabla.setColumnIdentifiers(cabecera);        
                Object[] datos = new Object[4];

                    for(int i =0; i<prestamo.getcn();i++){
                        datos[0] = arregloNodo[i].getPrestamo().getFechaP();
                        datos[1] = arregloNodo[i].getPrestamo().getFechaR();
                        datos[2] = arregloNodo[i].getPrestamo().getProrroga();
                        datos[3] = arregloNodo[i].getPrestamo().getIncumpli();
           
            prestamo.Recorrer();
            tabla.addRow(datos);
                   
        TextModi.setText("Mostrando datos guardados de los Préstamos");
            
        }
        Tabla.setModel(tabla);
    }//GEN-LAST:event_MostrarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Alumno;
    private javax.swing.JMenuItem IngreAlum;
    private javax.swing.JMenuItem IngreLibro;
    private javax.swing.JMenuItem IngrePres;
    private javax.swing.JMenu Libro;
    private javax.swing.JMenuItem MostrarA;
    private javax.swing.JMenuItem MostrarL;
    private javax.swing.JMenuItem MostrarP;
    private javax.swing.JMenu Préstamo;
    private javax.swing.JScrollPane Resu;
    private javax.swing.JMenu Salir;
    private javax.swing.JTable Tabla;
    public javax.swing.JLabel TextModi;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
